/** portable-hack-ast-extras is MIT licensed, see /LICENSE. */
namespace HTL\Pha\_Private;

// @see https://github.com/facebook/hhvm/blob/09f6283fcdbdac9b4ec19768d809ee7d2012e612/hphp/hack/src/parser/hh_autoimport.ml
const keyset<string> AUTO_IMPORTED_TYPES = keyset[
  'AnyArray',
  'AsyncFunctionWaitHandle',
  'AsyncGenerator',
  'AsyncGeneratorWaitHandle',
  'AsyncIterator',
  'AsyncKeyedIterator',
  'Awaitable',
  'AwaitAllWaitHandle',
  'classname',
  'Collection',
  'ConcurrentWaitHandle',
  'ConditionWaitHandle',
  'Container',
  'darray',
  'dict',
  'ExternalThreadEventWaitHandle',
  'IMemoizeParam',
  'UNSAFESingletonMemoizeParam',
  'ImmMap',
  'ImmSet',
  'ImmVector',
  'InvariantException',
  'Iterable',
  'Iterator',
  'KeyedContainer',
  'KeyedIterable',
  'KeyedIterator',
  'KeyedTraversable',
  'keyset',
  'Map',
  'ObjprofObjectStats',
  'ObjprofPathsStats',
  'ObjprofStringStats',
  'Pair',
  'RescheduleWaitHandle',
  'ResumableWaitHandle',
  'Set',
  'Shapes',
  'SleepWaitHandle',
  'StaticWaitHandle',
  'supportdyn',
  'Traversable',
  'typename',
  'TypeStructure',
  'TypeStructureKind',
  'varray_or_darray',
  'varray',
  'vec_or_dict',
  'vec',
  'Vector',
  'WaitableWaitHandle',
  'XenonSample',
];
