/** portable-hack-ast-extras is MIT licensed, see /LICENSE. */
namespace HTL\Pha\_Private;

// @see https://github.com/facebook/hhvm/blob/09f6283fcdbdac9b4ec19768d809ee7d2012e612/hphp/hack/src/parser/hh_autoimport.ml
const keyset<string> AUTO_IMPORTED_FUNCTIONS = keyset[
  'asio_get_current_context_idx',
  'asio_get_running_in_context',
  'asio_get_running',
  'class_meth',
  'darray',
  'dict',
  // Added by hand
  'die',
  // Added by hand
  'exit',
  'fun',
  'heapgraph_create',
  'heapgraph_dfs_edges',
  'heapgraph_dfs_nodes',
  'heapgraph_edge',
  'heapgraph_foreach_edge',
  'heapgraph_foreach_node',
  'heapgraph_foreach_root',
  'heapgraph_node_in_edges',
  'heapgraph_node_out_edges',
  'heapgraph_node',
  'heapgraph_stats',
  'idx',
  'idx_readonly',
  'inst_meth',
  'invariant_callback_register',
  'invariant_violation',
  'invariant',
  'is_darray',
  'is_dict',
  'is_keyset',
  'is_varray',
  'is_vec',
  'keyset',
  'meth_caller',
  'objprof_get_data',
  'objprof_get_paths',
  'server_warmup_status',
  'thread_mark_stack',
  'thread_memory_stats',
  'type_structure',
  'type_structure_for_alias',
  'varray',
  'vec',
  'xenon_get_data',
];
